name: cola38
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip=23.1.2
  - pytorch=1.13.1
  - cpuonly
  - pip:
    - gymnasium==0.29.1
    - mujoco==2.3.3
    - imageio==2.35.1
    - cython==0.29.35
    - numpy==1.21.6
    - scipy==1.7.3
    - pymoo==0.6.0
    - opencv-python==4.7.0.72
    - matplotlib==3.5.3
    - tensorboard==2.11.2
    - wandb==0.18.7
    - visdom==0.2.4
